name: Deploy Staging Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging # Uses Secrets bound to the 'staging' GitHub environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Create .env file
        run: |
          cat << 'EOF' > .env
          REACT_APP_STRIPE_PUBLISHABLE_KEY=${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}
          VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}
          EOF

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --ignore-engines || yarn install --ignore-engines
          yarn add -D webpack webpack-cli --ignore-engines

      - name: Build frontend production bundle
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npx webpack --mode production --progress
